service: zzip-backend
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  httpApi:
    cors: true
    authorizers:
      zzipAuthorizer:
        type: request
        functionName: auth_authorizer
        identitySource: $request.header.Authorization
        enableSimpleResponses: true
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stage: dev
  environment:
    STAGE: ${env:STAGE, "dev"}
    JWT_SECRET_KEY: ${ssm:/${self:service}/${env:STAGE, "dev"}/jwt_secret_key}
    NAVER_CLIENT_SECRET: ${ssm:/${self:service}/${env:STAGE, "dev"}/naver_client_secret}
    GOOGLE_CLIENT_SECRET: ${ssm:/${self:service}/${env:STAGE, "dev"}/google_client_secret}

custom:
  esbuild:
    sourcemap: true

functions:
  hello:
    handler: src/hello/get.handler
    events:
      - httpApi:
          path: /hello
          method: get
  signin_apple:
    handler: src/signin/apple/post.handler
    events:
      - httpApi:
          path: /signin/apple
          method: post
  signin_naver:
    handler: src/signin/naver/post.handler
    events:
      - httpApi:
          path: /signin/naver
          method: post
  signin_kakao:
    handler: src/signin/kakao/post.handler
    events:
      - httpApi:
          path: /signin/kakao
          method: post
  token_access_get:
    handler: src/token/access/get.handler
    events:
      - httpApi:
          path: /token/access
          method: get
  token_refresh_delete:
    handler: src/token/refresh/delete.handler
    events:
      - httpApi:
          path: /token/refresh
          method: delete
          authorizer: zzipAuthorizer
  user_get:
    handler: src/user/get.handler
    events:
      - httpApi:
          path: /user
          method: get
          authorizer: zzipAuthorizer
  user_put:
    handler: src/user/put.handler
    events:
      - httpApi:
          path: /user
          method: put
          authorizer: zzipAuthorizer
  user_delete:
    handler: src/user/delete.handler
    events:
      - httpApi:
          path: /user
          method: delete
          authorizer: zzipAuthorizer
